name: test-adopt-info
base: core18
adopt-info: version
summary: Set the snap version programmatically
description: |
  Boilerplate

grade: devel
confinement: strict

parts:
  version:
    plugin: nil
    source: version
    override-pull: |
      PROJECT_VERSION=$(cat $SNAPCRAFT_PROJECT_DIR/version/current)
      GIT_REVISION=$(git rev-parse --short HEAD)
      snapcraftctl set-version ${PROJECT_VERSION}-$(date +%Y%m%d%H%M%S)+${GIT_REVISION}
